import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/ui/organisms/Header";
import { Footer } from "@/ui/molecules/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Men`s store - Next13 E-Commerce",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Header />
				<section className="sm:py-18 mx-auto flex w-full max-w-2xl flex-grow flex-col px-8 py-12 sm:px-6 lg:max-w-7xl">
					{children}
				</section>
				{/* <footer>
					<p className="text-center text-sm text-gray-500">
						Next13 e-commerce © {new Date().getFullYear()}{" "}
					</p>
				</footer> */}
				<Footer />
			</body>
		</html>
	);
}
